### ISSUE TITLE
https://atlas-test.fly.dev/morphology/lemma/146682/#paradigm

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/atlas-data-prep#2]
We need to filter out comparative and superlatives (easily done with the postag).

That also means having separate paradigms for them.

![image](https://github.com/user-attachments/assets/2ab0ffd7-1031-4342-833d-272aae51599b)

**Comment by jtauber** [comment]
Could do with a little more styling but degree is broken out now into different paradigms.
